import React from 'react'
import Head from 'next/head'

const Header = () => (
  <Head>
    <title>IA - APP</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default Header
